# Generated by Django 5.2.17 on 2026-09-30 21:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_profile_picture_experience_availability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerequest',
            name='exchange_type',
            field=models.CharField(choices=[('credit', 'Credit Exchange'), ('direct', 'Direct Skill Exchange')], default='credit', max_length=10),
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='offered_skill',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='requested_skill',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddConstraint(
            model_name='exchangerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('exchange_type', 'direct'), ('status__in', ['pending', 'accepted', 'scheduled'])), fields=('requester', 'provider', 'listing', 'offered_skill', 'requested_skill'), name='unique_active_direct_exchange'),
        ),
    ]
