# Generated by Django 5.2.17 on 2026-09-30 21:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_exchangerequest_exchange_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exchangerequest',
            name='unique_active_direct_exchange',
        ),
        migrations.AddConstraint(
            model_name='exchangerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('exchange_type', 'direct'), ('status__in', ['pending', 'accepted', 'scheduled'])), fields=('requester', 'provider', 'offered_skill', 'requested_skill'), name='unique_active_direct_exchange'),
        ),
    ]
